[package]
name = "libmsi"
version = "0.1.0"
edition = "2018"

[build-dependencies.bindgen]
version = "^0.59.1"
default-features = false
# static or runtime
features = ["runtime"]

[build-dependencies.regex]
version = "^1.5.4"
default-features = false
features = ["std", "unicode"]

[dependencies]
gio-sys = "^0.14.0"
glib-sys = "^0.14.0"
glib = "^0.14.8"
