[package]
name = 'filter-ffxiv-log'
version = '0.1.0'
edition = '2021'
rust-version = '1.76.0'

[dependencies]
anyhow = '1.0.80'

[[bin]]
name = 'filter-ffxiv-log'
path = 'main.rs'

[profile.release]
strip = true
lto = true
