on:
  push:
    branches: [filter-ffxiv-log]

env:
  CARGO_TERM_COLOR: always

jobs:
  filter-ffxiv-log:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
        key: cargo-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-r1
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: filter-ffxiv-log-${{ matrix.os }}
        path: target/release/filter-ffxiv-log${{ startsWith(matrix.os, 'windows') && '.exe' || '' }}
        if-no-files-found: error
        compression-level: 9
