# vim: sw=2
name: Build
on: push

jobs:
  tt:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install mtools
    - run: type curl tar install mmd mcopy mksquashfs xorriso node zstd
    - uses: actions/checkout@v4
    - run: >
        curl --silent --get --output ./bootstrap.tar.gz
        https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.gz

    # - uses: actions/cache@v3
    #   id: pacman-cache
    #   with:
    #     path: root.x86_64/var/cache/pacman/pkg/
    #     key: >
    #       pacman-packages-r1-${{ runner.os }}-${{
    #       hashFiles('bootstrap.tar.gz')
    #       }}-${{
    #       hashFiles('packages.x86_64')
    #       }}
    # - run: sudo chown -hR 0 ./root.x86_64
    #   name: github troubles
    #   if: steps.pacman-cache.outputs.cache-hit == 'true'

    - run: sudo tar xzf ./bootstrap.tar.gz --numeric-owner
    - run: >
        sudo install -d -m 0755 -g 0 -o 0 ./fs/ &&
        sudo mount --bind ./root.x86_64 ./fs/
    - run: sudo cp -af --no-preserve=ownership,mode ./airootfs/. ./fs/
    - name: permissions
      run: >
        sudo chmod -R 400 ./fs/etc/shadow &&
        sudo chmod -R 750 ./fs/root/ &&
        sudo chmod -R 755 ./fs/usr/bin/lwm &&
        sudo install -d -m 0755 -g 0 -o 0 ./fs/efi/

    - run: >
        echo 'sudo ./fs/bin/arch-chroot ./fs/ "$@"' > ./chroot &&
        chmod +x ./chroot
    - run: >
        sudo install -m 0644 -g 0 -o 0
        pacman.conf ./fs/etc/pacman.conf
    - run: ./chroot pacman-key --init
    - run: ./chroot pacman-key --populate
    - run: ./chroot pacman -Syu --noconfirm $(grep -Ev '^(#|$)' packages.x86_64)
    - run: >
        sudo install -m 0644 -g 0 -o 0
        airootfs/etc/pacman.conf ./fs/etc/pacman.conf

    - run: |
        set -euxf

        mkfs.fat -C -n XNUKISO_EFI ./boot $(
          node -pe '
            (Math.ceil(
              fs.statSync("./fs/efi/arch.efi").size / (1024 * 1024)
            ) + 1) * 1024
          '
        )

        mmd -i ./boot ::/EFI ::/EFI/BOOT
        sudo mcopy -i ./boot ./fs/efi/arch.efi ::/EFI/BOOT/BOOTx64.EFI

    - name: cleanup
      run: |
        ./chroot rm -r \
          /efi \
          /boot \
          /var/lib/pacman \
          /var/cache/pacman/pkg \
          /var/log \
          /var/tmp
        ./chroot fd . / -e pacnew -e pacsave -e pacorig -X rm

    - run: sudo install -d -m 0755 -g 0 -o 0 ./iso/arch/x86_64/
    - run: >
        sudo mksquashfs ./fs/ ./iso/arch/x86_64/airootfs.sfs -noappend
        -comp xz -Xbcj x86 -b 1M -Xdict-size 1M
    - run: sudo umount ./fs/
    - run: sha512sum airootfs.sfs | sudo tee ./iso/arch/x86_64/airootfs.sfs.sha512

    - run: >
        xorriso
        -no_rc
        -as mkisofs -iso-level 3 -full-iso9660-filenames -joliet -joliet-long
        -rational-rock
        -volid "XNUK_ARCH_DICK"
        -appid "Xnuk Shuman Dick"
        -publisher "Xnuk Shuman"
        -partition_offset 16
        -append_partition 2 C12A7328-F81F-11D2-BA4B-00A0C93EC93B ./boot
        -appended_part_as_gpt
        -eltorito-alt-boot
        -e --interval:appended_partition_2:all::
        -no-emul-boot
        -output root.iso
        ./iso/

    - run: |
        sha256sum root.iso > root.iso.sha256sum
        b2sum root.iso > root.iso.b2sum

    - uses: actions/upload-artifact@v3
      with:
        name: root.iso
        path: root.iso*
